# Generated by Django 4.1.5 on 2023-07-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('contact', models.CharField(default=0, max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'administrateur',
            },
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_permis', models.CharField(max_length=30)),
                ('Categorie_permis', models.CharField(max_length=1)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chauffeur',
            },
        ),
        migrations.CreateModel(
            name='Momo_transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_requete', models.CharField(max_length=25)),
                ('statuscode', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=30)),
                ('numero_transaction', models.BigIntegerField()),
                ('montant', models.FloatField()),
                ('reference_operateur_id', models.BigIntegerField()),
                ('operateur', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('user_id', models.IntegerField(default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'momo_transaction',
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'proprietaire',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_reservation', models.CharField(max_length=10, unique=True)),
                ('nb_place', models.IntegerField()),
                ('latitude_pickup', models.FloatField()),
                ('longitude_pickup', models.FloatField()),
                ('statut_paiement', models.BooleanField(default=False)),
                ('canal_paiement', models.CharField(default='', max_length=20)),
                ('transaction_id', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('prix', models.FloatField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'db_table': 'trajet',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateTimeField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('portefeuille', models.FloatField(default=0)),
                ('is_voyageur', models.BooleanField(default=False)),
                ('is_fournisseur', models.BooleanField(default=False)),
                ('is_chauffeur', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Wallet_transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('solde_initial', models.FloatField()),
                ('solde_restant', models.FloatField()),
                ('service', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestiontoursinterurbains.reservation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestiontoursinterurbains.utilisateur')),
            ],
            options={
                'db_table': 'wallet_transaction',
            },
        ),
        migrations.CreateModel(
            name='Voyageur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiontoursinterurbains.utilisateur')),
            ],
            options={
                'db_table': 'voyageur',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=25)),
                ('visite_technique', models.BooleanField(default=True)),
                ('plaque', models.CharField(max_length=15)),
                ('statut', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('nb_place', models.IntegerField()),
                ('proprietaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontoursinterurbains.proprietaire')),
            ],
            options={
                'db_table': 'vehicule',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tour', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=50)),
                ('statut', models.BooleanField(default=True)),
                ('nb_reservation', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('heure', models.TimeField()),
                ('capacite', models.IntegerField()),
                ('chauffeur_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiontoursinterurbains.chauffeur')),
                ('trajet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontoursinterurbains.trajet')),
                ('vehicule_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiontoursinterurbains.vehicule')),
            ],
            options={
                'db_table': 'tour',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gestiontoursinterurbains.tour'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='transaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='voyageur_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontoursinterurbains.voyageur'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontoursinterurbains.utilisateur'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontoursinterurbains.utilisateur'),
        ),
    ]
