# Generated by Django 4.1.5 on 2023-08-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontoursinterurbains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momo_transaction',
            name='message',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='momo_transaction',
            name='operateur',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='momo_transaction',
            name='statuscode',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
