# Generated by Django 4.1.5 on 2023-07-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontoursinterurbains', '0002_alter_administrateur_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
